<div id="advertisingpopup" class="popup">
	<div class="popupContent">
	<h1>Advertising that works</h1>
	<p>We will develop a plan of advertising tailored to your firm or company's overall
		marketing strategy so that it best segments the target market for your message.
		In today's world, budget is crucial and we always seek to maximize impact so that
		resources are not wasted on costly advertising that does not work. Maximizing
		the number of exposures will have a direct relationship to the number of sales/behavior changes generated by the actual advertising promotion. Before we start an
		advertising campaign, we hold a face-to-face meeting with the client and gain a full
		understanding of the marketing plan and corporate mission statement. We then
		devise several strategies and promotional ads to help differentiate your product or
		service within the market.</p>
	<p>Having the right message for a select targeted group will help to improve the
		effectiveness of your advertising campaign and will optimize the value of your
		communication budget. All ads will include a "catchy," clever, attention-grabbing
		headline and a prominent call for action. <span class="bold">We want advertising to work for you.</span></p>
	</div>
</div>
<div id="brandingpopup" class="popup">
	<div class="popupContent">
	<h1 style="font-size:17px;">Corporate Branding to Distinguish Your Company from the Competition</h1>
	<p>HWDS and Associates, Inc. develops brand strategies for your unique corporate
		identity. A solid brand identity builds lasting customer loyalty that produces
		compelling market results.</p>
	<p>Before undertaking a brand redesign, it is important for a company to develop and/or review its strategic marketing plan. For maximum effectiveness, a brand supports
		and is in sync with the goals and strategies outlined in the corporate marketing plan.
		We can help write or rewrite a plan for your firm or organization.</p>
	<p>Building a recognizable corporate "mark", inviting typographic treatment,
		consistent "look" and a distinct tagline is the foundation for a successful rebranding
		campaign. Indeed, establishing a consistent brand promotes customer loyalty
		and makes a product or service easily identifiable and memorable. HWDS creates
		successful brand strategies so that your firm can outshine the competition in a
		global market.</p>
	</div>
</div>
<div id="promotingpopup" class="popup">
	<div class="popupContent">
	<h1>Promotions that Produce Results</h1>
	<p>We are experts in creating distinctive and memorable corporate promotions.
		Whether it is an event, a marketing blitz, an awareness campaign, or a product
		launch, we have the right solution for your company. Let us demonstrate how we
		can devise a kick-off promotion that includes a unique give-away or an e-blast that
		reaches out to the target audience. Contests, raffles, celebrity endorsements, and
		corporate sponsorships can generate "buzz" for an event. Have us create a vehicle
		wrap, back drop display or street banners for your promotional campaign. For
		our clients, we have imprinted logos and messages on beach towels, mugs, koozie
		bottles and packs, t-shirts, pens, cups and mugs, bags, hats as well as novelty items.
		In addition, we have designed dozens of stunning enamel lapel pins for a host of
		clients including Metrolink, Norwalk Transit, the Orange County Transportation
		Commission and Kaiser Permanente.</p>
	</div>
</div>
<div id="webmarketingpopup" class="popup">
	<div class="popupContent">
		<h1 style="font-size:17px;">Online Solutions to Maximize Your Company's Marketing Potential</h1>
		<p>Whether it's a new Web site, Web portal, e-commerce site, Flash animation, e-newsletter, e-card or e-blast, 
			we can tailor the right interactive solution for your company. Let us demonstrate how you can use the Web 
			effectively to promote your company, save print costs and deliver and update your message quickly and 
			effectively. We can develop state-of-the-art solutions to differentiate your company,
			product or service from the competition and to drive visitors to your Web site.</p>
	</div>
</div>
<div id="clientspopup" class="popup">
	<div class="popupContent">
		<ul class="bullets threecol">
			<li class="h1 orange">Our Clients include:</li>
			<li><span>City of Orange, CA</span></li>
			<li><span>City of Santa Monica </span></li>
			<li><span>Kaiser Permanente</span></li>
			<li><span>LLG Engineers</span></li>
			<li><span>Los Angeles Metropolitan </br>Transportation Authority (Metro)</span></li>
			<li><span>Metropolitan Washington Council of Governments</span></li>
			<li><span>Southern California Regional Rail Authority (Metrolink)</span></li>
			<li><span>Time Warner Cable</span></li>
			
		</ul>
        <ul class="bullets threecol">
			<li class="h1 orange">Partnered with </br>Pathways for:</li>
			<li><span>Children's Hospital Los Angeles</span></li>
			<li><span>Cherriots Rideshare (Salem, OR)</span></li>
			<li><span>City of Norwalk</span></li>
			<li><span>MetroWest/Pulte Homes</span></li>
			<li><span>Norwalk Transit Systems</span></li>
			<li><span>Potomac Crossing Consultants </span></li>
			<li><span>Tashman &amp; Associates </span></li>
			<li><span>Transportation Management  Services</span></li>
			<li><span>Washington D.C. Recycling Program</span></li>
            <li><span>WomenandWords.com</span></li>
		</ul>
        
        </ul>
        <ul class="bullets threecol">
			<li class="h1 orange">We have also designed materials for:</li>
			<li><span>City of Los Angeles/National Preservation Partners</span></li>
			<li><span>Orange County Transportation Commission (OCTA)</span></li>
			<li><span>San Bernardino Associated Governments (SANBAG)</span></li>
			<li><span>Ventura County Transportation Commission (VCTC)</span></li>
			<li><span>City of Santa Clarita</span></li>
            <li><span>Robin Lewin Productions</span></li>
		</ul>
	</div>
</div>
<div id="contactuspopup" class="popup">
	<div>
		<iframe src="https://docs.google.com/spreadsheet/embeddedform?formkey=dGdQb1RJd0h1QThWNklpb0dzTHo0SHc6MA" width="700" height="500" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>
	</div>
</div>
<div id="ecardspopup" class="popup popupBig">
	<div class="popupContent" id="ecardsmain">
		<img src="images/popups/ECardsscreens.png" usemap="#ecards-map" border="0" width="800" height="566" alt=""/>
		<map id="_ecards-map" name="ecards-map">
			<area shape="rect" coords="515,36,749,171" class="ecardflash" rel="#ecard0popup" alt="HWDS Holiday Card 2010" title="HWDS Holiday Card 2010"/>
			<area shape="rect" coords="48,178,284,344" class="ecardflash" rel="#ecard1popup" alt="LLG Holiday Card 2009" title="LLG Holiday Card 2009"/>
			<area shape="rect" coords="295,188,510,334" class="ecardflash" rel="#ecard2popup" alt="HWDS Halloween Card 2008" title="HWDS Halloween Card 2008"/>
			<area shape="rect" coords="517,186,753,334" class="ecardflash" rel="#ecard3popup" alt="Metrolink Holiday Card 2010" title="Metrolink Holiday Card 2010"/>
			<area shape="rect" coords="58,384,303,513" class="ecardflash" rel="#ecard4popup" alt="HWDS Holiday Card 2007" title="HWDS Holiday Card 2007"/>
			<area shape="rect" coords="340,376,575,518" class="ecardflash" rel="#ecard5popup" alt="LLG 2011 Holiday Card" title="LLG 2011 Holiday Card"/>
			<area shape="rect" coords="613,350,741,516" class="ecardflash" rel="#ecard6popup" alt="HWDS 2012 Holiday Card" title="HWDS 2012 Holiday Card"/>
		</map>
	</div>
	<!--start sub-popups for ecards -->
	<div class="popupswap" ng-repeat="flashecard in flashecards" id="ecard{{flashecard.id}}popup">
		<div class="returnClick"><a class="ecardsreturn" href="#">Return to Ecards Section</a></div>
		<div class="popupContent">
			<div id="ecardflashcontent{{flashecard.id}}">
				<h1>You need Flash to view the proper content.</h1>
				<img height="{{flashecard.h}}" width="{{flashecard.w}}" ng-src="images/popups/ecards/{{flashecard.img}}"/>
			</div>
		</div>
	</div>
	<!--end sub-popups for ecards -->
</div>
<div id="flipbookspopup" class="popup popupBig">
	<div class="popupContent" id="flipbooksmain">
		<img src="images/popups/Flipbookspopup.png" usemap="#flipbooks-map" border="0" width="800" height="566" alt=""/>
		<map id="_flipbooks-map" name="flipbooks-map">
			<area shape="rect" coords="32,89,352,258" class="flipbookscontent" rel="#flipbook0popup" alt="Metrolink 20th Anniversary Report" title="Metrolink 20th Anniversary Report"/>
			<area shape="rect" coords="458,90,785,259" class="flipbookscontent" rel="#flipbook1popup" alt="MWCOG State of the Commute Report" title="MWCOG State of the Commute Report"/>
			<area shape="rect" coords="157,262,683,420" class="flipbookscontent" rel="#flipbook2popup" alt="Metrolink 15th Anniversary Annual Report" title="Metrolink 15th Anniversary Annual Report"/>
			<area shape="rect" coords="152,422,790,561" class="flipbookscontent" rel="#flipbook3popup" alt="Norwalk Transit Annual Report" title="Norwalk Transit Annual Report"/>
		</map>
	</div>
	<div class="popupswap" id="flipbooks0popup">
		<div class="returnClick"><a class="flipbooksreturn" href="#">Return to Flipbooks Section</a></div>
		<div class="popupContent">
			<div>
				<iframe src="http://www.metrolinktrains.com/pdfs/20thAnniversaryReport/" width="700" height="500" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>
			</div>
		</div>
	</div>
	<div class="popupswap" id="flipbooks1popup">
		<div class="returnClick"><a class="flipbooksreturn" href="#">Return to Flipbooks Section</a></div>
		<div class="popupContent">
			<div>
				<iframe src="/UniflipBooks/StateofCommute/" width="700" height="500" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>
			</div>
		</div>
	</div>
	<div class="popupswap" id="flipbooks2popup">
		<div class="returnClick"><a class="flipbooksreturn" href="#">Return to Flipbooks Section</a></div>
		<div class="popupContent">
			<div>
				<iframe src="/UniflipBooks/Metrolink15thAnniversaryReport/" width="700" height="500" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>
			</div>
		</div>
	</div>
	<div class="popupswap" id="flipbooks3popup">
		<div class="returnClick"><a class="flipbooksreturn" href="#">Return to Flipbooks Section</a></div>
		<div class="popupContent">
			<div>
				<iframe src="/UniflipBooks/NTAnnualReport/" width="700" height="500" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>
			</div>
		</div>
	</div>
</div>
<div id="timelesspopup" class="popup popupBig">
	<div id="timelessmain">
		<img src="images/popups/Timeless.png" usemap="#timeless-map" border="0" width="800" height="566" alt=""/>
		<map id="_timeless-map" name="timeless-map">
			<area shape="rect" coords="76,107,687,209" class="timelesscontent" rel="#timeless0popup" alt="Stuff A Bus" title="Stuff A Bus"/>
			<area shape="rect" coords="79,250,690,395" class="timelesscontent" rel="#timeless1popup" alt="CommuteSmart News" title="CommuteSmart News"/>
			<area shape="rect" coords="73,402,684,547" class="timelesscontent" rel="#timeless2popup" alt="Holiday Train Poster" title="Holiday Train Poster"/>
		</map>
	</div>

	<!--start sub-popups for timeless -->
	<div class="popupswap" id="timeless0popup">
		<div class="returnClick"><a class="timelessreturn" href="#">Return to Timeless Section</a></div>
		<div id="stuffabusmain">
			<div class="popupContent">
				<img src="images/popups/timeless/Stuff-A-Bus/11-Years-of-Stuff-A-Bus-MAIN.png" usemap="#timeless-stuffabus-map" border="0" width="760" height="538" alt=""/>
				<map id="_timeless-stuffabus-map" name="timeless-stuffabus-map">
					<area shape="rect" coords="10,99,157,211" class="stuffabuscontent" rel="#2002" alt="Stuff-A-Bus 2002" title="Stuff-A-Bus 2002"/>
					<area shape="rect" coords="182,94,351,208" class="stuffabuscontent" rel="#2003" alt="Stuff-A-Bus 2003" title="Stuff-A-Bus 2003"/>
					<area shape="rect" coords="377,92,544,207" class="stuffabuscontent" rel="#2004" alt="Stuff-A-Bus 2004" title="Stuff-A-Bus 2004"/>
					<area shape="rect" coords="564,105,747,206" class="stuffabuscontent" rel="#2005" alt="Stuff-A-Bus 2005" title="Stuff-A-Bus 2005"/>
					<area shape="rect" coords="36,250,235,356" class="stuffabuscontent" rel="#2008" alt="Stuff-A-Bus 2008" title="Stuff-A-Bus 2008"/>
					<area shape="rect" coords="248,248,487,357" class="stuffabuscontent" rel="#2007" alt="Stuff-A-Bus 2007" title="Stuff-A-Bus 2007"/>
					<area shape="rect" coords="498,248,714,357" class="stuffabuscontent" rel="#2006" alt="Stuff-A-Bus 2006" title="Stuff-A-Bus 2006"/>
					<area shape="rect" coords="42,402,204,511" class="stuffabuscontent" rel="#2009" alt="Stuff-A-Bus 2009" title="Stuff-A-Bus 2009"/>
					<area shape="rect" coords="213,410,394,514" class="stuffabuscontent" rel="#2010" alt="Stuff-A-Bus 2010" title="Stuff-A-Bus 2010"/>
					<area shape="rect" coords="408,400,572,513" class="stuffabuscontent" rel="#2011" alt="Stuff-A-Bus 2011" title="Stuff-A-Bus 2011"/>
					<area shape="rect" coords="584,400,741,516" class="stuffabuscontent" rel="#2012" alt="Stuff-A-Bus 2012" title="Stuff-A-Bus 2012"/>
				</map>
			</div>
		</div>
	</div>
	<div class="popupswap" id="timeless1popup">
		<div class="returnClick"><a class="timelessreturn" href="#">Return to Timeless Section</a></div>
		<div id="csnmain">
			<img src="images/popups/timeless/CommuteSmart News/9-Years-of-Commute-Smart-News-MAIN.png" usemap="#timeless-csn-map" border="0" width="760" height="538" alt=""/>
			<map id="_timeless-csn-map" name="timeless-csn-map">
				<area shape="rect" coords="50,78,228,207" class="csncontent" rel="#2005" alt="CommuteSmart News 2005" title="CommuteSmart News 2005"/>
				<area shape="rect" coords="270,75,448,204" class="csncontent" rel="#2006" alt="CommuteSmart News 2006" title="CommuteSmart News 2006"/>
				<area shape="rect" coords="485,73,663,202" class="csncontent" rel="#2007" alt="CommuteSmart News 2007" title="CommuteSmart News 2007"/>
				<area shape="rect" coords="517,225,695,354" class="csncontent" rel="#2008" alt="CommuteSmart News 2008" title="CommuteSmart News 2008"/>
				<area shape="rect" coords="314,227,492,356" class="csncontent" rel="#2009" alt="CommuteSmart News 2009" title="CommuteSmart News 2009"/>
				<area shape="rect" coords="101,223,279,352" class="csncontent" rel="#2010" alt="CommuteSmart News 2010" title="CommuteSmart News 2010"/>
				<area shape="rect" coords="58,383,236,520" class="csncontent" rel="#2011" alt="CommuteSmart News 2011" title="CommuteSmart News 2011"/>
				<area shape="rect" coords="272,381,450,518" class="csncontent" rel="#2012" alt="CommuteSmart News 2012" title="CommuteSmart News 2012"/>
				<area shape="rect" coords="479,383,657,516" class="csncontent" rel="#2013" alt="CommuteSmart News 2013" title="CommuteSmart News 2013"/>
			</map>
		</div>
	</div>
	<div class="popupswap" id="timeless2popup">
		<div class="returnClick"><a class="timelessreturn" href="#">Return to Timeless Section</a></div>
		<div id="trainmain">
			<img src="images/popups/timeless/Holiday Train Posters/9-Years-of-Holiday-Train-Poster-MAIN.png" usemap="#timeless-train-map" border="0" width="760" height="538" alt=""/>
			<map id="_timeless-train-map" name="timeless-train-map">
				<area shape="rect" coords="70,75,227,207" class="traincontent" rel="#2003" alt="Holiday Train Poster 2003" title="Holiday Train Poster 2003"/>
				<area shape="rect" coords="277,75,447,205" class="traincontent" rel="#2004" alt="Holiday Train Poster 2004" title="Holiday Train Poster 2004"/>
				<area shape="rect" coords="488,75,665,208" class="traincontent" rel="#2005" alt="Holiday Train Poster 2005" title="Holiday Train Poster 2005"/>
				<area shape="rect" coords="95,223,272,356" class="traincontent" rel="#2008" alt="Holiday Train Poster 2008" title="Holiday Train Poster 2008"/>
				<area shape="rect" coords="313,226,480,359" class="traincontent" rel="#2007" alt="Holiday Train Poster 2007" title="Holiday Train Poster 2007"/>
				<area shape="rect" coords="519,224,688,357" class="traincontent" rel="#2006" alt="Holiday Train Poster 2006" title="Holiday Train Poster 2006"/>
				<area shape="rect" coords="69,383,235,517" class="traincontent" rel="#2009" alt="Holiday Train Poster 2009" title="Holiday Train Poster 2009"/>
				<area shape="rect" coords="276,382,447,516" class="traincontent" rel="#2010" alt="Holiday Train Poster 2010" title="Holiday Train Poster 2010"/>
				<area shape="rect" coords="483,383,654,517" class="traincontent" rel="#2011" alt="Holiday Train Poster 2011" title="Holiday Train Poster 2011"/>
			</map>
		</div>
	</div>
	<!--end sub-popups for timeless -->

	<!--start sub-popups for Stuff-A-Bus -->
	<div class="popupswap" id="stuffabus2002popup">
		<div class="returnClick"><a class="stuffabusreturn" href="#">Return to Stuff-A-Bus Main Section</a></div>
		<img class="subpop" src="images/popups/timeless/Stuff-A-Bus/Stuff-A-Bus-2002.png" border="0" width="737" height="517" alt="2002 Stuff-A-Bus"/>
	</div>
	<div class="popupswap" id="stuffabus2003popup">
		<div class="returnClick"><a class="stuffabusreturn" href="#">Return to Stuff-A-Bus Main Section</a></div>
		<img class="subpop" src="images/popups/timeless/Stuff-A-Bus/Stuff-A-Bus-2003.png" border="0" width="737" height="517" alt="2003 Stuff-A-Bus"/>
	</div>
	<div class="popupswap" id="stuffabus2004popup">
		<div class="returnClick"><a class="stuffabusreturn" href="#">Return to Stuff-A-Bus Main Section</a></div>
		<img class="subpop" src="images/popups/timeless/Stuff-A-Bus/Stuff-A-Bus-2004.png" border="0" width="737" height="517" alt="2004 Stuff-A-Bus"/>
	</div>
	<div class="popupswap" id="stuffabus2005popup">
		<div class="returnClick"><a class="stuffabusreturn" href="#">Return to Stuff-A-Bus Main Section</a></div>
		<img class="subpop" src="images/popups/timeless/Stuff-A-Bus/Stuff-A-Bus-2005.png" border="0" width="737" height="517" alt="2005 Stuff-A-Bus"/>
	</div>
	<div class="popupswap" id="stuffabus2006popup">
		<div class="returnClick"><a class="stuffabusreturn" href="#">Return to Stuff-A-Bus Main Section</a></div>
		<img class="subpop" src="images/popups/timeless/Stuff-A-Bus/Stuff-A-Bus-2006.png" border="0" width="737" height="517" alt="2006 Stuff-A-Bus"/>
	</div>
	<div class="popupswap" id="stuffabus2007popup">
		<div class="returnClick"><a class="stuffabusreturn" href="#">Return to Stuff-A-Bus Main Section</a></div>
		<img class="subpop" src="images/popups/timeless/Stuff-A-Bus/Stuff-A-Bus-2007.png" border="0" width="737" height="517" alt="2007 Stuff-A-Bus"/>
	</div>
	<div class="popupswap" id="stuffabus2008popup">
		<div class="returnClick"><a class="stuffabusreturn" href="#">Return to Stuff-A-Bus Main Section</a></div>
		<img class="subpop" src="images/popups/timeless/Stuff-A-Bus/Stuff-A-Bus-2008.png" border="0" width="737" height="517" alt="2008 Stuff-A-Bus"/>
	</div>
	<div class="popupswap" id="stuffabus2009popup">
		<div class="returnClick"><a class="stuffabusreturn" href="#">Return to Stuff-A-Bus Main Section</a></div>
		<img class="subpop" src="images/popups/timeless/Stuff-A-Bus/Stuff-A-Bus-2009.png" border="0" width="737" height="517" alt="2009 Stuff-A-Bus"/>
	</div>
	<div class="popupswap" id="stuffabus2010popup">
		<div class="returnClick"><a class="stuffabusreturn" href="#">Return to Stuff-A-Bus Main Section</a></div>
		<img class="subpop" src="images/popups/timeless/Stuff-A-Bus/Stuff-A-Bus-2010.png" border="0" width="737" height="517" alt="2010 Stuff-A-Bus"/>
	</div>
	<div class="popupswap" id="stuffabus2011popup">
		<div class="returnClick"><a class="stuffabusreturn" href="#">Return to Stuff-A-Bus Main Section</a></div>
		<img class="subpop" src="images/popups/timeless/Stuff-A-Bus/Stuff-A-Bus-2011.png" border="0" width="737" height="517" alt="2011 Stuff-A-Bus"/>
	</div>
	<div class="popupswap" id="stuffabus2012popup">
		<div class="returnClick"><a class="stuffabusreturn" href="#">Return to Stuff-A-Bus Main Section</a></div>
		<img class="subpop" src="images/popups/timeless/Stuff-A-Bus/Stuff-A-Bus-2012.png" border="0" width="737" height="517" alt="2012 Stuff-A-Bus"/>
	</div>
	<!--end sub-popups for Stuff-A-Bus -->

	<!--start sub-popups for CommuteSmart News -->
	<div class="popupswap" id="csn2005popup">
		<div class="returnClick"><a class="csnreturn" href="#">Return to CommuteSmart News Main Section</a></div>
		<img class="subpop" src="images/popups/timeless/CommuteSmart News/csn10-2005.png" border="0" width="461" height="597" alt="2005 CommuteSmart News"/>
	</div>
	<div class="popupswap" id="csn2006popup">
		<div class="returnClick"><a class="csnreturn" href="#">Return to CommuteSmart News Main Section</a></div>
		<img class="subpop" src="images/popups/timeless/CommuteSmart News/csn09-2006.png" border="0" width="461" height="597" alt="2006 CommuteSmart News"/>
	</div>
	<div class="popupswap" id="csn2007popup">
		<div class="returnClick"><a class="csnreturn" href="#">Return to CommuteSmart News Main Section</a></div>
		<img class="subpop" src="images/popups/timeless/CommuteSmart News/csn08-2007.png" border="0" width="461" height="597" alt="2007 CommuteSmart News"/>
	</div>
	<div class="popupswap" id="csn2008popup">
		<div class="returnClick"><a class="csnreturn" href="#">Return to CommuteSmart News Main Section</a></div>
		<img class="subpop" src="images/popups/timeless/CommuteSmart News/csn11-2008.png" border="0" width="461" height="597" alt="2008 CommuteSmart News"/>
	</div>
	<div class="popupswap" id="csn2009popup">
		<div class="returnClick"><a class="csnreturn" href="#">Return to CommuteSmart News Main Section</a></div>
		<img class="subpop" src="images/popups/timeless/CommuteSmart News/csn09-2009.png" border="0" width="461" height="597" alt="2009 CommuteSmart News"/>
	</div>
	<div class="popupswap" id="csn2010popup">
		<div class="returnClick"><a class="csnreturn" href="#">Return to CommuteSmart News Main Section</a></div>
		<img class="subpop" src="images/popups/timeless/CommuteSmart News/csn10-2010.png" border="0" width="461" height="597" alt="2010 CommuteSmart News"/>
	</div>
	<div class="popupswap" id="csn2011popup">
		<div class="returnClick"><a class="csnreturn" href="#">Return to CommuteSmart News Main Section</a></div>
		<img class="subpop" src="images/popups/timeless/CommuteSmart News/csn10-2011.png" border="0" width="461" height="597" alt="2011 CommuteSmart News"/>
	</div>
	<div class="popupswap" id="csn2012popup">
		<div class="returnClick"><a class="csnreturn" href="#">Return to CommuteSmart News Main Section</a></div>
		<img class="subpop" src="images/popups/timeless/CommuteSmart News/csn06-2012.png" border="0" width="461" height="597" alt="2012 CommuteSmart News"/>
	</div>
	<div class="popupswap" id="csn2013popup">
		<div class="returnClick"><a class="csnreturn" href="#">Return to CommuteSmart News Main Section</a></div>
		<img class="subpop" src="images/popups/timeless/CommuteSmart News/csn01-2013.png" border="0" width="461" height="597" alt="2013 CommuteSmart News"/>
	</div>
	<!--end sub-popups for CommuteSmart News -->

	<!--start sub-popups for Holiday Train Poster -->
	<div class="popupswap" id="train2003popup">
		<div class="returnClick"><a class="trainreturn" href="#">Return to Holiday Train Poster Main Section</a></div>
		<img class="subpop" src="images/popups/timeless/Holiday Train Posters/Holiday-Train-Poster-2003.png" border="0" width="388" height="600" alt="2003 Holiday Train Poster"/>
	</div>
	<div class="popupswap" id="train2004popup">
		<div class="returnClick"><a class="trainreturn" href="#">Return to Holiday Train Poster Main Section</a></div>
		<img class="subpop" src="images/popups/timeless/Holiday Train Posters/Holiday-Train-Poster-2004.png" border="0" width="447" height="597" alt="2004 Holiday Train Poster"/>
	</div>
	<div class="popupswap" id="train2005popup">
		<div class="returnClick"><a class="trainreturn" href="#">Return to Holiday Train Poster Main Section</a></div>
		<img class="subpop" src="images/popups/timeless/Holiday Train Posters/Holiday-Train-Poster-2005.png" border="0" width="444" height="622" alt="2005 Holiday Train Poster"/>
	</div>
	<div class="popupswap" id="train2006popup">
		<div class="returnClick"><a class="trainreturn" href="#">Return to Holiday Train Poster Main Section</a></div>
		<img class="subpop" src="images/popups/timeless/Holiday Train Posters/Holiday-Train-Poster-2006.png" border="0" width="439" height="630" alt="2006 Holiday Train Poster"/>
	</div>
	<div class="popupswap" id="train2007popup">
		<div class="returnClick"><a class="trainreturn" href="#">Return to Holiday Train Poster Main Section</a></div>
		<img class="subpop" src="images/popups/timeless/Holiday Train Posters/Holiday-Train-Poster-2007.png" border="0" width="437" height="628" alt="2007 Holiday Train Poster"/>
	</div>
	<div class="popupswap" id="train2008popup">
		<div class="returnClick"><a class="trainreturn" href="#">Return to Holiday Train Poster Main Section</a></div>
		<img class="subpop" src="images/popups/timeless/Holiday Train Posters/Holiday-Train-Poster-2008.png" border="0" width="437" height="629" alt="2008 Holiday Train Poster"/>
	</div>
	<div class="popupswap" id="train2009popup">
		<div class="returnClick"><a class="trainreturn" href="#">Return to Holiday Train Poster Main Section</a></div>
		<img class="subpop" src="images/popups/timeless/Holiday Train Posters/Holiday-Train-Poster-2009.png" border="0" width="438" height="630" alt="2009 Holiday Train Poster"/>
	</div>
	<div class="popupswap" id="train2010popup">
		<div class="returnClick"><a class="trainreturn" href="#">Return to Holiday Train Poster Main Section</a></div>
		<img class="subpop" src="images/popups/timeless/Holiday Train Posters/Holiday-Train-Poster-2010.png" border="0" width="437" height="601" alt="2010 Holiday Train Poster"/>
	</div>
	<div class="popupswap" id="train2011popup">
		<div class="returnClick"><a class="trainreturn" href="#">Return to Holiday Train Poster Main Section</a></div>
		<img class="subpop" src="images/popups/timeless/Holiday Train Posters/Holiday-Train-Poster-2011.png" border="0" width="441" height="606" alt="2011 Holiday Train Poster"/>
	</div>
	<!--end sub-popups for Holiday Train Poster -->
</div>
<div id="greenpopup" class="popup">
	<h1>Our commitment to the environment:</h1>
	<ul class="bullets">
		<li><span>We design publications that use recycled or synthetic papers.</span></li>
		<li><span>We design materials that use soy-based inks.</span></li>
		<li><span>We promote Teleworking from offsite work locations such as local business centers or home offices.</span></li>
		<li><span>We regularly use teleconferencing, conference calls and the Internet to help keep cars off the road.</span></li>
		<li><span>We create communications for solid waste disposal, recycling, air quality management, ridesharing and bicycling, all of which help to promote a greener planet and healthier lifestyle. We have been producing these types of public service materials and campaigns for more than 20 years.</span></li>
		<li><span>We develop e-newsletters, e-blasts and Web sites to reduce paper consumption.</span></li>
		<li><span>We recycle all outdated computer equipment and media at city-certified recycling centers.</span></li>
		<li><span>We encourage our employees to stay fit, eat healthy, exercise regularly and "live green" to promote a better quality of life and a healthy work ethic.</span></li>
	</ul>
</div>